List<String> cuisines = [
  "Any cuisine",
  "Angolan cuisine",
  "Cameroonian cuisine",
  "Chadian cuisine",
  "Congolese cuisine",
  "Centrafrican cuisine",
  "Equatorial Guinea cuisine",
  "Gabonese cuisine",
  "Santomean cuisine",
  "Burundian cuisine",
  "Comorian cuisine",
  "Djiboutian cuisine",
  "Eritrean cuisine",
  "Ethiopian cuisine",
  "Ethiopian Jewish cuisine",
  "Kenyan cuisine",
  "Maasai cuisine",
  "Malagasy cuisine",
  "Malawian cuisine",
  "Mauritian cuisine",
  "Mozambican cuisine",
  "Rwandan cuisine",
  "Seychellois cuisine",
  "Somali cuisine",
  "Sudanese cuisine",
  "South Sudanese cuisine",
  "Tanzanian cuisine",
  "Zanzibari cuisine",
  "Ugandan cuisine",
  "Zambian cuisine",
  "Zimbabwean cuisine",
  "Algerian cuisine",
  "Berber cuisine",
  "Egyptian cuisine",
  "Libyan cuisine",
  "Moroccan cuisine",
  "Tunisian cuisine",
  "Western Saharan cuisine",
  "Botswana cuisine",
  "Eswatini cuisine",
  "Lesotho cuisine",
  "Namibian cuisine",
  "South African cuisine",
  "Afrikaner cuisine",
  "Benin cuisine",
  "Burkinabé cuisine",
  "Cape Verdean cuisine",
  "Gambian cuisine",
  "Ghanaian cuisine",
  "Guinean cuisine",
  "Guinea-Bissauan cuisine",
  "Ivorian cuisine",
  "Liberian cuisine",
  "Malian cuisine",
  "Mauritanian cuisine",
  "Niger cuisine",
  "Nigerian cuisine",
  "Saint Helenian cuisine",
  "Senegalese cuisine",
  "Sierra Leone cuisine",
  "Togolese cuisine",
  "Latin American cuisine",
  "Native American cuisine",
  "Inuit cuisine",
  "Tlingit cuisine",
  "Bermudian cuisine",
  "Canadian cuisine",
  "Canadian Chinese cuisine",
  "Cuisine of the Maritimes",
  "Cuisine of Quebec",
  "Cuisine of Toronto",
  "Greenlandic cuisine",
  "Inuit cuisine",
  "Mexican cuisine",
  "Cuisine of Chiapas",
  "Cuisine of Mexico City",
  "Oaxacan cuisine",
  "Cuisine of Veracruz",
  "Mesoamerican cuisine",
  "Ancient Maya cuisine",
  "Aztec cuisine",
  "Mexican-American cuisine",
  "Cali-Mex cuisine",
  "Korean-Mexican fusion",
  "New Mexican cuisine",
  "Tex-Mex cuisine",
  "Tlingit cuisine",
  "Midwestern American cuisine",
  "Cuisine of Chicago",
  "Cuisine of North Dakota",
  "Cuisine of Omaha",
  "Cuisine of St. Louis",
  "Cuisine of Wisconsin",
  "Minnesotan cuisine",
  "Iron Range cuisine",
  "Northeastern American cuisines",
  "Cuisine of New England",
  "Cuisine of the Mid-Atlantic United States",
  "Cuisine of Baltimore",
  "Cuisine of New Jersey",
  "Cuisine of New York City",
  "Cuisine of the Pennsylvania Dutch",
  "Cuisine of Philadelphia",
  "Cuisine of Pittsburgh",
  "Southern American cuisine",
  "Cuisine of Atlanta",
  "Floribbean cuisine",
  "Cuisine of Kentucky",
  "Louisiana Creole cuisine",
  "Cajun cuisine",
  "Cuisine of New Orleans",
  "Lowcountry cuisine",
  "Soul food",
  "Southwestern American cuisine",
  "New Mexican cuisine",
  "Texan cuisine",
  "Tex-Mex cuisine",
  "Western American cuisine",
  "Cuisine of California",
  "California cuisine",
  "Korean-Mexican fusion",
  "Hawaiian cuisine",
  "Pacific Northwest cuisine",
  "Rocky Mountain cuisine",
  "Fusion cuisine",
  "American Jewish cuisine",
  "Cajun cuisine",
  "Chinese American cuisine",
  "Filipino-American cuisine",
  "Floribbean cuisine",
  "German-American cuisine",
  "Greek-American cuisine",
  "Indian-American cuisine",
  "Italian-American cuisine",
  "Japanese-American cuisine",
  "Korean-American cuisine",
  "Korean-Mexican fusion",
  "Mexican-American cuisine",
  "Cali-Mex cuisine",
  "New Mexican cuisine",
  "Tex-Mex cuisine",
  "Cuisine of the Pennsylvania Dutch",
  "Thai-American cuisine",
  "Vietnamese-American cuisine",
  "New American cuisine",
  "Belizean cuisine",
  "Costa Rican cuisine",
  "Guatemalan cuisine",
  "Honduran cuisine",
  "Mesoamerican cuisine",
  "Ancient Maya cuisine",
  "Nicaraguan cuisine",
  "Panamanian cuisine",
  "Salvadoran cuisine",
  "Argentinian cuisine",
  "Bolivian cuisine",
  "Brazilian cuisine",
  "Chilean cuisine",
  "Colombian cuisine",
  "Muisca cuisine",
  "Ecuadorian cuisine",
  "French Guianan cuisine",
  "Guyanese cuisine",
  "Paraguayan cuisine",
  "Cuisine of Asunción",
  "Peruvian cuisine",
  "Peruvian-Chinese cuisine",
  "Inca cuisine",
  "Surinamese cuisine",
  "Uruguayan cuisine",
  "Cuisine of Montevideo",
  "Venezuelan cuisine",
  "Caribbean cuisine",
  "Anguillan cuisine",
  "Antigua and Barbuda cuisine",
  "Aruban cuisine",
  "Bahamian cuisine",
  "Barbadian cuisine",
  "Belizean cuisine",
  "British Virgin Islands cuisine",
  "Cayman Islands cuisine",
  "Caribbean Chinese cuisine",
  "Cuban cuisine",
  "Curaçao cuisine",
  "Dominica cuisine",
  "Dominican Republic cuisine",
  "Floribbean cuisine",
  "French Guianan cuisine",
  "Grenadian cuisine",
  "Guyanese cuisine",
  "Haitian cuisine",
  "Jamaican cuisine",
  "Martinican cuisine",
  "Montserrat cuisine",
  "Puerto Rican cuisine",
  "St. Kitts and Nevis cuisine",
  "Saint Lucian cuisine",
  "Surinamese cuisine",
  "Trinidad and Tobago cuisine",
  "Turks and Caicos cuisine",
  "US Virgin Islands cuisine",
  "Afghan cuisine",
  "Hazara cuisine",
  "Pashtun cuisine",
  "Azerbaijani cuisine",
  "Balochi cuisine",
  "Bashkir cuisine",
  "Bukharan Jewish cuisine",
  "Dagestani cuisine",
  "Iranian cuisine",
  "Caspian cuisine",
  "Kurdish cuisine",
  "Karakalpak cuisine",
  "Kazakh cuisine",
  "Koryo-saram cuisine",
  "Kyrgyz cuisine",
  "Tajik cuisine",
  "Tatar cuisine",
  "Turkmen cuisine",
  "Uyghur cuisine",
  "Uzbek cuisine",
  "Japanese cuisine",
  "Ainu cuisine",
  "Kaiseki",
  "Okinawan cuisine",
  "Japanese regional cuisine",
  "Nagoya cuisine",
  "Japanese fusion food",
  "Japanese-American cuisine",
  "Japanese Chinese cuisine",
  "Shippoku",
  "Hawaiian cuisine",
  "Itameshi",
  "Yoshoku",
  "Korean cuisine",
  "Korean Chinese cuisine",
  "Korean regional cuisine",
  "Korean royal court cuisine",
  "Korean temple cuisine",
  "Koryo-saram cuisine",
  "North Korean cuisine",
  "Sakhalin Korean cuisine",
  "South Korean cuisine",
  "Korean-Mexican fusion",
  "Vietnamese cuisine",
  "Chinese cuisine",
  "Beijing cuisine",
  "Chinese aristocrat cuisine",
  "Chinese imperial cuisine",
  "Hebei cuisine",
  "Henan cuisine",
  "Northeastern Chinese cuisine",
  "Heilongjiang cuisine",
  "Jilin cuisine",
  "Liaoning cuisine",
  "Manchu cuisine",
  "Shandong cuisine",
  "Shanxi cuisine",
  "Tianjin cuisine",
  "Xuzhou cuisine",
  "Anhui cuisine",
  "Jiangsu cuisine",
  "Huaiyang cuisine",
  "Shanghai cuisine",
  "Haipai cuisine",
  "Zhejiang cuisine",
  "Hangbang cuisine",
  "Gansu cuisine",
  "Ningxia cuisine",
  "Qinghai cuisine",
  "Shaanxi cuisine",
  "Guilin cuisine",
  "Guizhou cuisine",
  "Hubei cuisine",
  "Hunan cuisine",
  "Jiangxi cuisine",
  "Sichuan cuisine",
  "Tujia cuisine",
  "Yunnan cuisine",
  "Cantonese cuisine",
  "Guangxi cuisine",
  "Hong Kong cuisine",
  "Macanese cuisine",
  "Hakka cuisine",
  "Min cuisine",
  "Fuzhou cuisine",
  "Hainan cuisine",
  "Minnan cuisine",
  "Putian (Henghwa) cuisine",
  "Chaoshan (Teochew) cuisine",
  "Ou cuisine",
  "Taiwan cuisine",
  "Hlai cuisine",
  "Kachin cuisine",
  "Miao cuisine",
  "Hmong cuisine",
  "Mongolian cuisine",
  "Tibetan cuisine",
  "Wa cuisine",
  "Xinjiang (Uyghur) cuisine",
  "Yao cuisine",
  "Yi cuisine",
  "Zhuang cuisine",
  "Chinese Buddhist cuisine",
  "Chinese Islamic cuisine",
  "Taoist diet",
  "American Chinese cuisine",
  "Australian Chinese cuisine",
  "British Chinese cuisine",
  "Burmese Chinese cuisine",
  "Cambodian Chinese cuisine",
  "Canadian Chinese cuisine",
  "Caribbean Chinese cuisine",
  "Filipino Chinese cuisine",
  "French Chinese cuisine",
  "Indian Chinese cuisine",
  "Indonesian Chinese cuisine",
  "Japanese Chinese cuisine",
  "Shippoku",
  "Latin American Chinese cuisine",
  "Cuban Chinese cuisine",
  "Mexican Chinese cuisine",
  "Peruvian Chinese cuisine",
  "Puerto Rican Chinese cuisine",
  "Korean Chinese cuisine",
  "Malaysian Chinese cuisine",
  "Mauritian Chinese cuisine",
  "New Zealand Chinese cuisine",
  "Pakistani Chinese cuisine",
  "Peranakan cuisine",
  "Singaporean Chinese cuisine",
  "Thai Chinese cuisine",
  "Vietnamese Chinese cuisine",
  "Bhutanese cuisine",
  "Mongolian cuisine",
  "Buryat cuisine",
  "Kalmyk cuisine",
  "Sikkimese cuisine",
  "Tibetan cuisine",
  "Tuvan cuisine",
  "Russian cuisine",
  "Buryat cuisine",
  "Chukchi cuisine",
  "Cuisine of Commander Islands",
  "Sakha cuisine",
  "Sakhalin Korean cuisine",
  "Yamal cuisine",
  "Yup'ik cuisine",
  "Bangladeshi cuisine",
  "Bengali cuisine",
  "Maldivian cuisine",
  "Nepalese cuisine",
  "Newari cuisine",
  "Sri Lankan cuisine",
  "Indian cuisine",
  "West Indian cuisine",
  "Goan cuisine",
  "Goan Catholic cuisine",
  "Gujarati cuisine",
  "Maharashtrian cuisine",
  "Malvani cuisine",
  "Parsi cuisine",
  "Rajasthani cuisine",
  "Sindhi cuisine",
  "North Indian cuisine",
  "Bhojpuri cuisine",
  "Kashmiri cuisine",
  "Maithil cuisine",
  "Mughlai cuisine",
  "Punjabi cuisine",
  "Rajasthani cuisine",
  "Uttar Pradesh cuisine",
  "Awadhi cuisine",
  "South Indian cuisine",
  "Karnataka cuisine",
  "Dakshina Karnataka cuisine",
  "Kodava cuisine",
  "Mangalurean cuisine",
  "Mangalurean Catholic cuisine",
  "Navyath Muslim cuisine",
  "Udupi cuisine",
  "Uttara Karnataka cuisine",
  "Kerala cuisine",
  "Tamil cuisine",
  "Chettinad cuisine",
  "Telugu cuisine",
  "Andhra cuisine",
  "Hyderabadi cuisine",
  "North East Indian cuisine",
  "Assamese cuisine",
  "Manipuri cuisine",
  "Meitei cuisine",
  "Mizo cuisine",
  "Naga cuisine",
  "Sikkimese cuisine",
  "Tripuri cuisine",
  "East Indian cuisine",
  "Bengali cuisine",
  "Bihari cuisine",
  "Jharkhandi cuisine",
  "Odia cuisine",
  "Oriya cuisine",
  "Other Indian cuisine",
  "Anglo-Indian cuisine",
  "Indo Caribbean food",
  "Indian Chinese cuisine",
  "Indian fast food",
  "Indo-Fijian food",
  "Indo-South African food",
  "Jain cuisine",
  "Malaysian Indian cuisine",
  "Pakistani cuisine",
  "Balochi cuisine",
  "Hazara cuisine",
  "Kashmiri cuisine",
  "Mughlai cuisine",
  "Muhajir cuisine",
  "Punjabi cuisine",
  "Lahori cuisine",
  "Saraiki cuisine",
  "Pashtun cuisine",
  "Sindhi cuisine",
  "Burmese cuisine",
  "Burmese Chinese cuisine",
  "Cambodian cuisine",
  "Cham cuisine",
  "Hmong cuisine",
  "Kachin cuisine",
  "Karen cuisine",
  "Manipuri cuisine",
  "Meitei cuisine",
  "Mizo cuisine",
  "Mon cuisine",
  "Naga cuisine",
  "Thai cuisine",
  "Lanna cuisine",
  "Lao cuisine",
  "Shan cuisine",
  "Southern Thai cuisine",
  "Thai-Chinese cuisine",
  "Tripuri cuisine",
  "Vietnamese cuisine",
  "Wa cuisine",
  "Bruneian cuisine",
  "Christmas Island cuisine",
  "East Timor cuisine",
  "Filipino cuisine",
  "Filipino-American cuisine",
  "Filipino Chinese cuisine",
  "Ilocano cuisine",
  "Kapampangan cuisine",
  "Mindanao cuisine",
  "Tagalog cuisine",
  "Visayan cuisine",
  "Malaysian cuisine",
  "Arab cuisine",
  "Eurasian cuisine",
  "Malay cuisine",
  "Malaysian Chinese cuisine",
  "Malaysian Indian cuisine",
  "Peranakan cuisine",
  "Sabahan cuisine",
  "Sarawakian cuisine",
  "Singaporean cuisine",
  "Acehnese cuisine",
  "Balinese cuisine",
  "Banjar cuisine",
  "Batak cuisine",
  "Indo cuisine",
  "Indonesian Arab cuisine",
  "Indonesian Chinese cuisine",
  "Indonesian Indian cuisine",
  "Javanese cuisine",
  "Betawi cuisine",
  "Madurese cuisine",
  "Sundanese cuisine",
  "Makassar cuisine",
  "Malay cuisine",
  "Manado cuisine",
  "Padang food",
  "Palembang cuisine",
  "Peranakan cuisine",
  "Arab cuisine",
  "Armenian cuisine",
  "Eastern Arabian cuisine",
  "Bahraini cuisine",
  "Emirati cuisine",
  "Kuwaiti cuisine",
  "Omani cuisine",
  "Qatari cuisine",
  "Saudi Arabian cuisine",
  "Yemeni cuisine",
  "Kurdish cuisine",
  "Levantine cuisine",
  "Iraqi cuisine",
  "Israeli cuisine",
  "Ancient Israelite cuisine",
  "Jordanian cuisine",
  "Lebanese cuisine",
  "Mizrahi Jewish cuisine",
  "Palestinian cuisine",
  "Syrian cuisine",
  "Syrian Jewish cuisine",
  "Assyrian cuisine",
  "Caucasian cuisine",
  "Azerbaijani cuisine",
  "Chechen cuisine",
  "Circassian cuisine",
  "Dagestani cuisine",
  "Georgian cuisine",
  "Ossetian cuisine",
  "Iranian cuisine",
  "Balochi cuisine",
  "Caspian cuisine",
  "Sephardic Jewish cuisine",
  "Turkish cuisine",
  "Pontic Greek cuisine",
  "Ashkenazi Jewish cuisine",
  "Austrian cuisine",
  "Viennese cuisine",
  "Czech cuisine",
  "Hungarian cuisine",
  "Liechtensteiner cuisine",
  "Polish cuisine",
  "Silesian cuisine",
  "Slovak cuisine",
  "Slovenian cuisine",
  "Swiss cuisine",
  "German cuisine",
  "German-American cuisine",
  "Austrian cuisine",
  "Viennese cuisine",
  "Baden cuisine",
  "Bavarian cuisine",
  "Brandenburg cuisine",
  "Franconian cuisine",
  "Hamburg cuisine",
  "Hessian cuisine",
  "Liechtensteiner cuisine",
  "Lower Saxon cuisine",
  "Mecklenburg cuisine",
  "Palatine cuisine",
  "Pomeranian cuisine",
  "Rhenish-Hessian cuisine",
  "Saxon cuisine",
  "Schleswig-Holstein cuisine",
  "Silesian cuisine",
  "Swabian cuisine",
  "Swiss cuisine",
  "Thuringian cuisine",
  "Eastern European cuisine",
  "Belarusian cuisine",
  "Cossack cuisine",
  "Russian cuisine",
  "Bashkir cuisine",
  "Chechen cuisine",
  "Circassian cuisine",
  "Komi cuisine",
  "Mordovian cuisine",
  "Tatar cuisine",
  "Udmurt cuisine",
  "Ukrainian cuisine",
  "Crimean Tatar cuisine",
  "Odesite cuisine",
  "Baltic cuisines",
  "Estonian cuisine",
  "Latvian cuisine",
  "Lithuanian cuisine",
  "Livonian cuisine",
  "Nordic cuisines",
  "Danish cuisine",
  "Faroese cuisine",
  "New Nordic cuisine",
  "Finnish cuisine",
  "Icelandic cuisine",
  "Norwegian cuisine",
  "Sami cuisine",
  "Swedish cuisine",
  "Balkan cuisine",
  "Albanian cuisine",
  "Kosovan cuisine",
  "Aromanian cuisine",
  "Bosnian cuisine",
  "Bulgarian cuisine",
  "Croatian cuisine",
  "Gagauz cuisine",
  "Macedonian cuisine",
  "Montenegrin cuisine",
  "Serbian cuisine",
  "Romani cuisine",
  "Romanian cuisine",
  "Moldovan cuisine",
  "Transylvanian Saxon cuisine",
  "Mediterranean cuisine",
  "Catalan cuisine",
  "Andorran cuisine",
  "Gibraltarian cuisine",
  "Greek cuisine",
  "Macedonian cuisine (Greek)",
  "Cretan cuisine",
  "Cypriot cuisine",
  "Cuisine of the Ionian Islands",
  "Epirotic cuisine",
  "Pontic Greek cuisine",
  "Asia Minor Greek cuisine",
  "Italian cuisine",
  "Abruzzese and Molisan cuisine",
  "Italian-American cuisine",
  "Arbëreshë cuisine",
  "Basilicatan (Lucanian) cuisine",
  "Calabrian cuisine",
  "Corsican cuisine",
  "Lazian or Roman",
  "Ligurian cuisine",
  "Lombard cuisine",
  "Mantuan cuisine",
  "Neapolitan cuisine",
  "Pugliese cuisine",
  "Sammarinese cuisine",
  "Sardinian cuisine",
  "Sicilian cuisine",
  "Tuscan cuisine",
  "Venetian cuisine",
  "Maltese cuisine",
  "Monégasque cuisine",
  "Occitan cuisine",
  "Portuguese cuisine",
  "Spanish cuisine",
  "Andalusian cuisine",
  "Asturian cuisine",
  "Aragonese cuisine",
  "Balearic cuisine",
  "Canarian cuisine",
  "Cantabrian cuisine",
  "Castilian-Leonese cuisine",
  "Castilian-Manchego cuisine",
  "Extremaduran cuisine",
  "Galician cuisine",
  "Leonese cuisine",
  "Madrid cuisine",
  "Minorcan cuisine",
  "Valencian cuisine",
  "Sephardic Jewish cuisine",
  "Western European cuisine",
  "Basque cuisine",
  "Belgian cuisine",
  "Dutch cuisine",
  "Frisian cuisine",
  "Limburgian cuisine",
  "French cuisine",
  "Cajun cuisine",
  "Haute cuisine",
  "Lyonnaise cuisine",
  "Nouvelle cuisine",
  "Occitan cuisine",
  "Cuisine of Quebec",
  "Luxembourgian cuisine",
  "British cuisine",
  "Anglo-Indian cuisine",
  "British Chinese cuisine",
  "Channel Islands cuisine",
  "English cuisine",
  "Cornish cuisine",
  "Devonian cuisine",
  "Dorset cuisine",
  "Northern Irish cuisine",
  "Scottish cuisine",
  "Welsh cuisine",
  "Cuisine of Carmarthenshire",
  "Cuisine of Ceredigion",
  "Cuisine of Gower",
  "Cuisine of Monmouthshire",
  "Cuisine of Pembrokeshire",
  "Irish cuisine",
  "Australasian cuisine",
  "Australian cuisine",
  "Australian Chinese cuisine",
  "Bush tucker",
  "Tasmanian cuisine",
  "New Zealand cuisine",
  "New Zealand Chinese cuisine",
  "Melanesian cuisine",
  "Bougainville cuisine",
  "Fijian cuisine",
  "New Caledonian cuisine",
  "Papua New Guinean cuisine",
  "Solomon Islands cuisine",
  "Vanuatuan cuisine",
  "Micronesian cuisine",
  "Kiribati cuisine",
  "Mariana Islands cuisine",
  "Guamanian cuisine",
  "Marshallese cuisine",
  "Nauruan cuisine",
  "Palauan cuisine",
  "Polynesian cuisine",
  "Cook Islands cuisine",
  "Hawaiian cuisine",
  "Niuean cuisine",
  "Pascuense (Easter Island) cuisine",
  "Pitcairn Islands cuisine",
  "Samoan cuisine",
  "Tahitian cuisine",
  "Tongan cuisine",
  "Tuvaluan cuisine",
  "Wallis and Futuna cuisine",
  "Fusion cuisine",
  "Haute cuisine",
  "Nouvelle cuisine",
  "Vegan cuisine",
  "Vegetarian cuisine",
  "Indian vegetarian cuisine",
  "Buddhist cuisine",
  "Chinese Buddhist cuisine",
  "Chinese Islamic cuisine",
  "Jewish cuisine",
  "American Jewish cuisine",
  "Ashkenazi Jewish cuisine",
  "Bukharan Jewish cuisine",
  "Ethiopian Jewish cuisine",
  "Mizrahi Jewish cuisine",
  "Sephardic Jewish cuisine",
  "Syrian Jewish cuisine",
  "Catholic diet cuisine",
  "Coptic Orthodox diet cuisine",
  "Ethiopian Orthodox diet cuisine",
  "Goan Catholic cuisine",
  "Mangalorean Catholic cuisine",
  "Mennonite cuisine",
  "Ancient Egyptian cuisine",
  "Ancient Greek cuisine",
  "Ancient Israelite cuisine",
  "Ancient Roman cuisine",
  "Aztec cuisine",
  "Byzantine cuisine",
  "Early modern European cuisine",
  "Historical Chinese cuisine",
  "Historical Indian cuisine",
  "Inca cuisine",
  "Maya cuisine",
  "Medieval cuisine",
  "Ottoman cuisine",
  "Peasant foods",
  "Soviet cuisine",
  "Thirteen Colonies cuisine"
];

List<String> cuisines_200 = [
  "Any cuisine",
  "Chinese cuisine",
  "Indian cuisine",
  "Italian cuisine",
  "Japanese cuisine",
  "French cuisine",
  "Mexican cuisine",
  "Thai cuisine",
  "Spanish cuisine",
  "Greek cuisine",
  "Vietnamese cuisine",
  "Korean cuisine",
  "American cuisine",
  "Turkish cuisine",
  "Lebanese cuisine",
  "Brazilian cuisine",
  "Caribbean cuisine",
  "Moroccan cuisine",
  "Ethiopian cuisine",
  "Indonesian cuisine",
  "British cuisine",
  "German cuisine",
  "Portuguese cuisine",
  "Peruvian cuisine",
  "Russian cuisine",
  "Israeli cuisine",
  "Egyptian cuisine",
  "Argentinian cuisine",
  "South African cuisine",
  "Cuban cuisine",
  "Malaysian cuisine",
  "Filipino cuisine",
  "Pakistani cuisine",
  "Iranian cuisine",
  "Nepalese cuisine",
  "Syrian cuisine",
  "Armenian cuisine",
  "Georgian cuisine",
  "Ukrainian cuisine",
  "Polish cuisine",
  "Hungarian cuisine",
  "Dutch cuisine",
  "Belgian cuisine",
  "Afghan cuisine",
  "Singaporean cuisine",
  "Cambodian cuisine",
  "Bangladeshi cuisine",
  "Tibetan cuisine",
  "Sri Lankan cuisine",
  "Tunisian cuisine",
  "Algerian cuisine",
  "Libyan cuisine",
  "Palestinian cuisine",
  "Cypriot cuisine",
  "Austrian cuisine",
  "Swiss cuisine",
  "Scottish cuisine",
  "Irish cuisine",
  "Swedish cuisine",
  "Norwegian cuisine",
  "Finnish cuisine",
  "Danish cuisine",
  "Icelandic cuisine",
  "Welsh cuisine",
  "Canadian cuisine",
  "Australian cuisine",
  "New Zealand cuisine",
  "Chilean cuisine",
  "Colombian cuisine",
  "Venezuelan cuisine",
  "Uruguayan cuisine",
  "Ecuadorian cuisine",
  "Bolivian cuisine",
  "Paraguayan cuisine",
  "Guatemalan cuisine",
  "Honduran cuisine",
  "Salvadoran cuisine",
  "Nicaraguan cuisine",
  "Costa Rican cuisine",
  "Panamanian cuisine",
  "Haitian cuisine",
  "Jamaican cuisine",
  "Puerto Rican cuisine",
  "Trinidad and Tobago cuisine",
  "Bahamian cuisine",
  "Barbadian cuisine",
  "Dominican Republic cuisine",
  "Burmese cuisine",
  "Lao cuisine",
  "Mongolian cuisine",
  "Kazakh cuisine",
  "Uzbek cuisine",
  "Tajik cuisine",
  "Kyrgyz cuisine",
  "Turkmen cuisine",
  "Saudi Arabian cuisine",
  "Iraqi cuisine",
  "Jordanian cuisine",
  "Kuwaiti cuisine",
  "Omani cuisine",
  "Qatari cuisine",
  "Emirati cuisine",
  "Bahraini cuisine",
  "Yemeni cuisine",
  "Sudanese cuisine",
  "Somali cuisine",
  "Kenyan cuisine",
  "Tanzanian cuisine",
  "Ugandan cuisine",
  "Rwandan cuisine",
  "Burundian cuisine",
  "Malawian cuisine",
  "Mozambican cuisine",
  "Zambian cuisine",
  "Zimbabwean cuisine",
  "Botswana cuisine",
  "Namibian cuisine",
  "Lesotho cuisine",
  "Eswatini cuisine",
  "Ghanaian cuisine",
  "Nigerian cuisine",
  "Senegalese cuisine",
  "Ivorian cuisine",
  "Cameroonian cuisine",
  "Benin cuisine",
  "Burkinabé cuisine",
  "Gambian cuisine",
  "Guinean cuisine",
  "Liberian cuisine",
  "Malian cuisine",
  "Nigerien cuisine",
  "Sierra Leone cuisine",
  "Togolese cuisine",
  "Angolan cuisine",
  "Congolese cuisine",
  "Centrafrican cuisine",
  "Equatorial Guinea cuisine",
  "Gabonese cuisine",
  "Santomean cuisine",
  "Eritrean cuisine",
  "Djiboutian cuisine",
  "Comorian cuisine",
  "Madagascar cuisine",
  "Mauritian cuisine",
  "Seychellois cuisine",
  "Cape Verdean cuisine",
  "Belizean cuisine",
  "Native American cuisine",
  "Greenlandic cuisine",
  "Cajun cuisine",
  "Hawaiian cuisine",
  "Alaskan cuisine",
  "Cuisine of Quebec",
  "Cuisine of Toronto",
  "Cuisine of Mexico City",
  "Oaxacan cuisine",
  "Cuisine of Veracruz",
  "Mesoamerican cuisine",
  "Cuisine of Chiapas",
  "New Mexican cuisine",
  "Tex-Mex cuisine",
  "Cali-Mex cuisine",
  "Mexican-American cuisine",
  "Cuisine of Chicago",
  "Cuisine of New York City",
  "Cuisine of the Pennsylvania Dutch",
  "Southern American cuisine",
  "Cuisine of New Orleans",
  "Soul food",
  "Texan cuisine",
  "Californian cuisine",
  "Pacific Northwest cuisine",
  "Fusion cuisine",
  "Okinawan cuisine",
  "Japanese regional cuisine",
  "Japanese fusion food",
  "Japanese-American cuisine",
  "Korean Chinese cuisine",
  "Korean royal court cuisine",
  "Korean temple cuisine",
  "South Korean cuisine",
  "Beijing cuisine",
  "Chinese imperial cuisine",
  "Shandong cuisine",
  "Sichuan cuisine",
  "Cantonese cuisine",
  "Shanghai cuisine",
  "Zhejiang cuisine",
  "Hunan cuisine",
  "Yunnan cuisine",
  "Hong Kong cuisine",
  "Macanese cuisine",
  "Taiwan cuisine",
  "Cuisine of Quebec",
  "Cuisine of Toronto",
  "Cuisine of Chicago",
  "Cuisine of New York City",
  "Cuisine of the Pennsylvania Dutch",
  "Southern American cuisine",
  "Cuisine of New Orleans",
  "Soul food",
  "Texan cuisine",
  "Californian cuisine",
  "Hawaiian cuisine",
  "Pacific Northwest cuisine",
  "Fusion cuisine",
  "Vegan cuisine",
  "Vegetarian cuisine",
  "Indian vegetarian cuisine",
  "Buddhist cuisine",
  "Chinese Buddhist cuisine",
  "Chinese Islamic cuisine",
  "Jewish cuisine",
  "American Jewish cuisine",
  "Ashkenazi Jewish cuisine",
  "Bukharan Jewish cuisine",
  "Ethiopian Jewish cuisine",
  "Mizrahi Jewish cuisine",
  "Sephardic Jewish cuisine",
  "Syrian Jewish cuisine",
  "Catholic diet cuisine",
  "Coptic Orthodox diet cuisine",
  "Ethiopian Orthodox diet cuisine",
  "Goan Catholic cuisine",
  "Mangalorean Catholic cuisine"
];
