// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJvfuZ-nhCkLRAQ3CP0kKUFDQlTAFYi2g',
    appId: '1:670291926367:web:f12b4d6fae22a09d446aea',
    messagingSenderId: '670291926367',
    projectId: 'smart-fridge-b2440',
    authDomain: 'smart-fridge-b2440.firebaseapp.com',
    storageBucket: 'smart-fridge-b2440.appspot.com',
    measurementId: 'G-ZTQMVFGHLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT-MnkQz-i20iWrDhWamHGiIOdCd0xqp0',
    appId: '1:670291926367:android:459d6e4d27cccd17446aea',
    messagingSenderId: '670291926367',
    projectId: 'smart-fridge-b2440',
    storageBucket: 'smart-fridge-b2440.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHJNE3L_TbT0LQGiONY7LvkWhk_7o3qfk',
    appId: '1:670291926367:ios:a0401d976e16dc0d446aea',
    messagingSenderId: '670291926367',
    projectId: 'smart-fridge-b2440',
    storageBucket: 'smart-fridge-b2440.appspot.com',
    iosClientId: '670291926367-aqoldo7boaebpkm5uqrjgqcopiiq9u72.apps.googleusercontent.com',
    iosBundleId: 'shop.uniplanet.smart-fridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHJNE3L_TbT0LQGiONY7LvkWhk_7o3qfk',
    appId: '1:670291926367:ios:56f7f7876a3744d3446aea',
    messagingSenderId: '670291926367',
    projectId: 'smart-fridge-b2440',
    storageBucket: 'smart-fridge-b2440.appspot.com',
    iosClientId: '670291926367-p2bs321u0a5a1ieu4kud5b5fmto77je2.apps.googleusercontent.com',
    iosBundleId: 'shop.uniplanet.smartfridge.smartFridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJvfuZ-nhCkLRAQ3CP0kKUFDQlTAFYi2g',
    appId: '1:670291926367:web:1e2545b7c6e7ea80446aea',
    messagingSenderId: '670291926367',
    projectId: 'smart-fridge-b2440',
    authDomain: 'smart-fridge-b2440.firebaseapp.com',
    storageBucket: 'smart-fridge-b2440.appspot.com',
    measurementId: 'G-KEYKXBP6MB',
  );
}
